### PR TITLE
Design Updates

### PR DESCRIPTION
**Pull request by bengroulx**
## What’s New
- Style sections
- Add new projects, adjust the grid
- Add the modal content, wire up
- Adjust copy throughout the site
- Adjust main body typeface

## To Do
- See the “modal” section in `script.js`; right now, there’s only one trigger for one modal… we need to be able to create a method of defining  which trigger initiates which modal so that we can have multiple modals.
- Should we inline the main stylesheet? Or use something like loadCSS? What do you think is a better experience?

### CODE REVIEW

**Comment by durfee** [comment]
Ready, pending #17 review

**Comment by bengroulx** [comment]
We gotta get rid of the hero video, it’s crippling performance :(

**Comment by durfee** [comment]
I think everything is pretty much ready to go here. Probably needs a final look over before merging with master

**Comment by durfee** [comment]
WE MERGIN

**Pull request merged**
